-- AlterTable
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "formatRefYoutubeId" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "formatRefTitle" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "formatRefUrl" TEXT;
